package com.quakbo.euler

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

fun fibonacci(): Sequence<Int> {
    return generateSequence(
            Pair(0, 1), { Pair(it.second, it.first + it.second) }).map { it.first }
}

const val limit = 4000000

fun main(args: Array<String>) {
    println(fibonacci()
            .takeWhile { it < limit }
            .filter { it % 2 == 0 }
            .sum())
}